site_name: Pneuron Docs
nav:
    - Home: index.md
    - About: about.md
    - Pneuron Design Studio:
        - Design Studio Overview: DesignStudioGuide.md
        - Basic Navigation: BasicNavigation.md
        - General Usage: GeneralUsage.md
        - Menu Commands And Functions: MenuCommandsAndFunctions.md
        - Project Menu Command And Functions: ProjectMenuCommandsAndFunctions.md
        - Pneuron Descriptions: PneuronDescriptions.md
        - Alias Descriptions: AliasDescriptions.md
        - Glossary And Terms: GlossaryAndTerms.md
    - Pneuron Enterprise Control Manager:
        - Enterprise Control Manager Overview: EnterpriseControlManagerGuide.md
        - Understanding The Enterprise Control Manager: UnderstandingPneuronEnterpriseControlManager.md
        - Using The Report Builder: UsingTheReportBuilder.md
        - Widget Descriptions: WidgetDescriptions.md
        - Working With Dashboards: WorkingWithDashboards.md
        - Working With Widgets: WorkingWithWidgets.md
    - Pneuron Administration:
        - Administration Overview: AdministrationGuide.md
        - Data Management: DataManagement.md
        - Managing Pneuron Sources: ManagingPneuronSources.md
        - Pneuron Security: PneuronSecurity.md
        - Understanding Pneuron Administration: UnderstandingPneuronAdministration.md
    - Pneuron Architecture:
        - Pneuron Architecture: PneuronArchitecture.md
        - Configuration Web Services: ConfigurationServices.md
        - License Web Services: LicenseServices.md
        - Message Web Services: MessageServices.md
        - Lock Web Services: LockServices.md
        - Monitoring Web Services: MonitoringServices.md
        - Robot Web Services: RobotServices.md
    - Installation:
        - Pneuron Installation (Linux): PneuronInstallationLinux.md
        - Pneuron Installation (Windows): PneuronInstallationWindows.md
theme: 
    name: readthedocs
    custom_dir: 'custom_theme'
    icon:
        wy-side-nav-search: [img/pn.png]
docs_dir: 'docs'
site_dir: 'site'
extra_css: [css/custom.css]
